apiVersion: v1
kind: Pod
metadata:
  name: client-a-xxx
  namespace: network-policy-b
  generateName: client-a-
  labels:
    pod-name: client-a
spec:
  containers:
    - args:
        - /bin/sh
        - -c
        - sleep 90000000
      name: client-a-container
      image: beyond.io:5000/fabric/x-tools:v1.0.0
  restartPolicy: Never
#  定向调度时使用
#  nodeSelector:
#    kubernetes:
#      kubernetes.io/hostname: wt-k8s-3
