apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: external-svc
  name: external-svc
  namespace: default
spec:
  clusterIP: 10.96.0.2
  ports:
  - port: 8089
    protocol: TCP
    targetPort: 8089
  sessionAffinity: None
  type: ClusterIP

---

apiVersion: v1
kind: Endpoints
metadata:
  labels:
    k8s-app: external-svc
  name: external-svc
  namespace: default
subsets:
- addresses:
  - ip: 10.40.20.208
  ports:
  - port: 8089
    protocol: TCP
