apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: x-tools
  namespace: default
spec:
  selector:
    matchLabels:
      name: x-tools
  template:
    metadata:
      labels:
        name: x-tools
    spec:
      containers:
      - image: beyond.io:5000/fabric/x-tools:v1.0.0
        name: x-tools
        resources:
          requests:
            memory: "5Mi"
            cpu: "5m"
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
      tolerations:
       - effect: NoSchedule
         operator: Exists
       - effect: NoExecute
         operator: Exists
       - key: CriticalAddonsOnly
         operator: Exists
       - key: "node-role.kubernetes.io/master"
         effect: "NoSchedule"
       - key: CriticalAddonsOnly
         operator: Exists


